services:

  nodered:

    image: nodered/node-red:5.0.1

    container_name: bms-nodered

    restart: unless-stopped

    ports:

      - "1880:1880"

    volumes:

      - ../nodered:/data

      - ../config:/config:ro

      - ../drivers:/drivers:ro

      - ../logs:/logs

      - ../backups:/backups

    environment:
      - TZ=America/Montevideo #configura la zona horaria

    ulimits:
      core:
        soft: 0
        hard: 0

  fuxa:

    image: frangoteam/fuxa:1.3.3

    container_name: bms-fuxa

    restart: unless-stopped

    ports:

      - "1881:1881"

    volumes:

      - ../fuxa/appdata:/usr/src/app/FUXA/server/_appdata

      - ../fuxa/db:/usr/src/app/FUXA/server/_db

      - ../fuxa/logs:/usr/src/app/FUXA/server/_logs

      - ../fuxa/images:/usr/src/app/FUXA/server/_images

    environment:

      - TZ=America/Montevideo

    depends_on:

      - nodered

  mosquitto:

    image: eclipse-mosquitto:2.0

    container_name: bms-mosquitto

    restart: unless-stopped

    ports:
      - "1883:1883"

    volumes:
      - ../mosquitto/config:/mosquitto/config
      - ../mosquitto/data:/mosquitto/data
      - ../mosquitto/log:/mosquitto/log

    environment:
      - TZ=America/Montevideo
